FROM arcnor/retro-toolchains-base

ADD buildroot/output/images/bittboy-buildroot.tar.gz /opt/

RUN mv /opt/bittboy-buildroot /opt/bittboy && cd /opt/bittboy && ./relocate-sdk.sh

ENV CROSS_TRIPLE %%CROSS_TRIPLE%%

ENV CROSS_ROOT /opt/bittboy/

ENV SYSROOT ${CROSS_ROOT}/${CROSS_TRIPLE}/sysroot/

ENV PATH ${PATH}:${CROSS_ROOT}/bin:${SYSROOT}/usr/bin

ENV ARCH arm

ENV CROSS_COMPILE ${CROSS_TRIPLE}-

WORKDIR /root
